# Site
repository: binchoi/binchoi.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bin Choi
title: Junior Backend Developer
email: binchoi@u.yale-nus.edu.sg
website: http://binchoi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  binchoi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: binchoi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: DSABlog
  icon: fas fa-globe
  url: https://binchoi.github.io/dsa-blog
- title: HabitRacer
  icon: fas fa-flag-checkered
  url: https://habitracer.com

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/LinkedIn_DP1.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Bin Choi. I'm a junior backend developer and a third-year student at Yale-NUS College. I am currently studying Computer Science at Aalto University in Finland as an exchange student.

  I enjoy logical problem solving and am deeply fascinated by the intersection of Medicine and Computer Science. Working with <mark>Spring Boot</mark> has taught me the importance of a well-structured MVC framework and Test-Driven Development. I have worked with a range of different languages and frameworks and am always looking for opportunities to work with something new. The languages that I currently have the most experience working with are: <mark>Java</mark>, <mark>Python</mark>, <mark>Scala</mark>, <mark>R</mark>, <mark>OCaml</mark>, and <mark>Bash/Linux</mark>.

  The idea of being able to create new services that positively impact countless lives is the driving force behind my back-end development journey. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Habit Racer
        link: www.habitracer.com
        # link_text: Project Website
        additional_links:
          - title:  binchoi/habit-racer
            icon: fab fa-github
            url: github.com/binchoi/habit-racer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Become a Habit Racer and fill two needs with one deed
        description: | # this will include new lines to allow paragraphs
          This is an application that developed from my own needs. Whether it be practicing for coding interviews or exercising regularly, I found habit building to be an incredibly difficult and lonely journey. To transform this uphill battle into an immersive and interactive recreation, I created HabitRacer - a competitve habit tracker that allows users to compete with their friends and family members over user-selected wagers while building new habits together. Users create/join races and record their daily success whenever they successfully keep to their habit; the user that recorded more successes at the end of the race is crowned champion and claims the wager. For each race, the service provides race statistics and visualizes the progress of each driver on a race track to keep up the user's motivation!
          
          I encountered many new tools and developed new and existing skills in the process of building this project. These include <mark>Spring Boot</mark>, <mark>AWS</mark> (i.e. EC2, S3, CodeDeploy), <mark>MariaDB</mark>, <mark>JUnit</mark>, <mark>GitHub Actions</mark>, <mark>Spring Data JPA</mark>, and <mark>Java</mark>. I also experienced the importance of Test-Driven Development, RESTful APIs, and software quality management. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Computational Biology
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: December 2020 - August 2021
        quote: >
          My small contribution to the improvement of cancer research
        description: | # this will include new lines to allow paragraphs
            Computer algorithms are heavily relied upon in cancer research, especially in in-vivo studies (e.g. Patient Derived Xenografts). Unfortunately, the state-of-the-art algorithms and tools don't work as well as they should. My research focused on analyzing the performance of these popular tools and developing an original pipeline that implements an Expectation-Maximization algorithm from an Empirical Bayesian perspective with <mark>Python</mark>, <mark>R</mark>, and <mark>Bash</mark>. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yale-NUS College
        caption: 2019 - 2023
        sub_title: BSc Mathematical, Computational, and Statistical Science (Computer Science track)
        quote: >
          Established in 2011 as a collaboration between Yale University and the National University of Singapore, Yale-NUS College is the first liberal arts college in Singapore. With an admit rate ranging from 3% to 7%, Yale-NUS College is an intimate liberal arts college dedicated to a community of learning. Founded by two great universities, In Asia, for the world.
        description: | # this will include new lines to allow paragraphs
          I have currently finished the second semester of my third year. This summer, I plan to take a Leave of Absence to fulfill my national service obligation in South Korea. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - I am South Korean but lived overseas in the Arabian Peninsula (in Dubai, Abu Dhabi, and Qatar) for most of my life (from age 6-18)
      - I run a data structures & algorithms blog at https://binchoi.github.io/leetcode/ 
      - I am documenting my back-end development learning process at https://bit.ly/375ez1P 
      - I like jazz 🎷😎
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
